name: tecylab_clase_04
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  themexpert: ^1.0.2
  shimmer: ^3.0.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  go_router: ^14.6.2
  bloc_concurrency: ^0.2.5
  path_provider: ^2.1.5
  fpdart: ^1.1.1
  sqflite: ^2.4.1
  hive_flutter: ^1.1.0
  path: ^1.9.0
  dio: ^5.7.0

  shared_preferences: ^2.3.3

  sembast: ^3.7.3
  sembast_web: ^2.4.0+2

  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1

dev_dependencies:
  freezed: ^2.5.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: EduAUVIC
      fonts:
        - asset: assets/fonts/EduAUVIC.ttf
    - family: Bokor-Regular
      fonts:
        - asset: assets/fonts/Bokor-Regular.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
