// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:373944059059:web:46b3718db28246d9b51cc6',
    messagingSenderId: '373944059059',
    projectId: 'tecylab',
    authDomain: 'tecylab.firebaseapp.com',
    storageBucket: 'tecylab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:373944059059:android:5990f8e21a7ea451b51cc6',
    messagingSenderId: '373944059059',
    projectId: 'tecylab',
    storageBucket: 'tecylab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:373944059059:ios:3b98902c8fdb5756b51cc6',
    messagingSenderId: '373944059059',
    projectId: 'tecylab',
    storageBucket: 'tecylab.firebasestorage.app',
    iosBundleId: 'com.tecylab.tecylabClase04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:373944059059:ios:3b98902c8fdb5756b51cc6',
    messagingSenderId: '373944059059',
    projectId: 'tecylab',
    storageBucket: 'tecylab.firebasestorage.app',
    iosBundleId: 'com.tecylab.tecylabClase04',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:373944059059:web:a6f00c87857df38cb51cc6',
    messagingSenderId: '373944059059',
    projectId: 'tecylab',
    authDomain: 'tecylab.firebaseapp.com',
    storageBucket: 'tecylab.firebasestorage.app',
  );
}
